
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: postgresql6.locum.ru
  username: lexx777_glidef56
  password: GFEfFd3Trq

development:
  <<: *default
  database: store_dev


test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: lexx777_glidef56
