# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  mail_password: <%= ENV["YANDEX_PASSWORD"] %>
  secret_key_base: 581f85f82ebe7853cb00f2e8fa4ac7ed2a2bb3806b483ee1cc001bf4d74dbb083762e94a4cfe70ae00ae33674894ea5438f488fc8b43d841105031e4bb999fe9

test:
  secret_key_base: 2f9eb6e3b594a6a4e9a4a9e37ca43147e7270e5785616dd6c786c3dcaed78a121c34cbaff21671bacb2a0a2309ca07407209ce266e0ce1cc324fc2e9ce100a51
  mail_password: <%= ENV["YANDEX_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>

production:
  mail_password: <%= ENV["YANDEX_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  secret_key_base: 553a253ff2420ca40780c7986c59cc6724d4f1ead4473c4f3d5f3c1da835ba5bb571829c7ef19e1fdff388c1db8763ce71afb4084dedcb3eefaa894d7d88f989
